apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "status-page.fullname" . }}
  namespace: {{ .Release.Namespace }}

  labels:
    {{- include "status-page.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.statusPage.replicaCount }}

  selector:
    matchLabels:
      {{- include "status-page.appSelectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "status-page.appSelectorLabels" . | nindent 8 }}

    spec:
      containers:
        - name: status-page

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          envFrom:
            - secretRef:
                name: {{ .Values.existingSecret }}

          {{- if .Values.redisHA.enabled }}
          env:
            - name: REDIS_SENTINELS
              value: {{ .Values.redisHA.sentinels | quote }}

            - name: REDIS_SENTINEL_SERVICE
              value: {{ .Values.redisHA.masterSet | quote }}

            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redisHA.authSecret | quote }}
                  key: {{ .Values.redisHA.authSecretKey | quote }}
          {{- end }}

          ports:
            - name: http
              containerPort: {{ .Values.statusPage.containerPort }}
              protocol: TCP

            - name: metrics
              containerPort: {{ .Values.statusPage.metrics.port }}
              protocol: TCP

          command:
            - /bin/sh
            - -c

          args:
            - |
              python manage.py collectstatic --noinput
              exec gunicorn statuspage.wsgi:application --bind 0.0.0.0:{{ .Values.statusPage.containerPort }}

          readinessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.statusPage.healthCheckHost | quote }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: http
              httpHeaders:
                - name: Host
                  value: {{ .Values.statusPage.healthCheckHost | quote }}
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            {{- toYaml .Values.statusPage.resources | nindent 12 }}
