image:
  repository: 992382545251.dkr.ecr.us-east-1.amazonaws.com/avivneta-status-page-dev
  tag: latest
  pullPolicy: Always

existingSecret: status-page-secrets

redisHA:
  enabled: true
  sentinels: "redis-ha-node-0.redis-ha-headless.status-page.svc.cluster.local:26379,redis-ha-node-1.redis-ha-headless.status-page.svc.cluster.local:26379,redis-ha-node-2.redis-ha-headless.status-page.svc.cluster.local:26379"
  masterSet: "status-page-master"
  authSecret: "redis-ha-auth"
  authSecretKey: "redis-password"

statusPage:
  replicaCount: 2
  containerPort: 8000

  metrics:
    enabled: true
    port: 8001
    interval: 30s

  service:
    type: ClusterIP
    port: 80

  healthCheckHost: app.avivneta-statuspage.com

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

worker:
  replicaCount: 2

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

scheduler:
  replicaCount: 1

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

redis:
  enabled: false

  replicaCount: 1

  image:
    repository: redis
    tag: "7"
    pullPolicy: IfNotPresent

  service:
    port: 6379

  persistence:
    enabled: true
    storageClass: gp2
    accessMode: ReadWriteOnce
    size: 1Gi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

ingress:
  enabled: true
  className: alb

  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: 'arn:aws:acm:us-east-1:992382545251:certificate/1e84d159-5280-42db-aa5a-cf0c225f592e'

  host: app.avivneta-statuspage.com
  path: /
  pathType: Prefix
